// @file packages/next/src/index.ts
// @description FCSS Next.js plugin — withFcss() wrapper for App Router and Pages Router.
// @layer adapters
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as url from 'node:url';

export interface FcssSafelistPattern {
  pattern: RegExp;
}

export interface FcssNextConfig {
  content?: string[];
  safelist?: Array<string | FcssSafelistPattern>;
}

const DEFAULT_CONTENT = [
  'app/**/*.{js,jsx,ts,tsx}',
  'pages/**/*.{js,jsx,ts,tsx}',
  'components/**/*.{js,jsx,ts,tsx}',
  'src/**/*.{js,jsx,ts,tsx}',
  '!node_modules/**',
  '!.next/**',
];

const CONFIG_FILENAMES = [
  'fcss.config.ts',
  'fcss.config.js',
  'fcss.config.mjs',
  'fcss.config.cjs',
] as const;

export async function loadFcssConfig(
  root: string,
): Promise<{ config: FcssNextConfig; configPath: string }> {
  for (const filename of CONFIG_FILENAMES) {
    const configPath = path.join(root, filename);
    if (!fs.existsSync(configPath)) continue;

    let raw: unknown;
    if (path.extname(configPath) === '.ts') {
      const { createJiti } = await import('jiti');
      const jiti = createJiti(configPath, { moduleCache: false });
      raw = await jiti.import(configPath, { default: true });
    } else {
      const mod = (await import(url.pathToFileURL(configPath).href)) as Record<string, unknown>;
      raw = mod['default'] ?? mod;
    }

    return { config: (raw as FcssNextConfig) ?? {}, configPath };
  }
  return { config: {}, configPath: '' };
}

export function resolveManifestPath(root: string): string {
  let dir = root;
  for (let i = 0; i < 6; i++) {
    const candidate = path.join(dir, 'node_modules/@fcss/core/dist/manifest.json');
    if (fs.existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(
    '[@fcss/next] Cannot find FCSS manifest. Install @fcss/core as a project dependency.',
  );
}

// Determines whether a CSS asset source contains an FCSS generated bundle.
function isFcssBundle(source: string): boolean {
  return source.includes('Generated by FCSS');
}

type WebpackCompiler = Record<string, unknown>;
type WebpackCompilation = Record<string, unknown>;
type WebpackAsset = { source(): string | Buffer; size?(): number; updateHash?(hash: unknown): void };
type RawSourceCtor = new (content: string) => WebpackAsset;

class FcssWebpackPlugin {
  private readonly dir: string;
  // Populated from compiler.webpack.sources in apply() for proper cache hash support.
  private RawSource: RawSourceCtor | undefined = undefined;

  constructor(dir: string) {
    this.dir = dir;
  }

  apply(compiler: WebpackCompiler): void {
    // Access webpack's bundled sources API for cache-hash-compatible asset replacement.
    const webpackApi = (compiler as Record<string, unknown>)['webpack'] as
      | { sources?: { RawSource?: RawSourceCtor } }
      | undefined;
    this.RawSource = webpackApi?.sources?.RawSource ?? undefined;

    const hooks = compiler['hooks'] as Record<string, unknown>;
    const thisCompilation = hooks['thisCompilation'] as {
      tap: (name: string, fn: (comp: WebpackCompilation) => void) => void;
    };

    thisCompilation.tap('FcssWebpackPlugin', (compilation) => {
      const compHooks = compilation['hooks'] as Record<string, unknown>;
      const processAssets = compHooks['processAssets'] as {
        tapPromise: (
          opts: { name: string; stage: number },
          fn: (assets: Record<string, WebpackAsset>) => Promise<void>,
        ) => void;
      };

      // Stage 100 = PROCESS_ASSETS_STAGE_OPTIMIZE: runs after mini-css-extract-plugin
      // emits CSS assets (stage -2000) and before css-minimizer-webpack-plugin (stage 400).
      processAssets.tapPromise(
        { name: 'FcssWebpackPlugin', stage: 100 },
        async (assets) => {
          await this.purgeAssets(compilation, assets);
        },
      );
    });
  }

  private makeSource(content: string): WebpackAsset {
    // Use webpack's RawSource when available so the caching layer can call updateHash().
    if (this.RawSource) return new this.RawSource(content);
    return {
      source: () => content,
      size: () => Buffer.byteLength(content, 'utf8'),
    };
  }

  private async purgeAssets(
    compilation: WebpackCompilation,
    assets: Record<string, WebpackAsset>,
  ): Promise<void> {
    const cssEntries = Object.entries(assets).filter(([name]) => name.endsWith('.css'));
    if (cssEntries.length === 0) return;

    const { config } = await loadFcssConfig(this.dir);
    const content = config.content ?? DEFAULT_CONTENT;
    const manifestPath = resolveManifestPath(this.dir);

    // ESM dynamic import works here because FcssWebpackPlugin is defined in ESM
    // (packages/next/dist/index.js) and its methods retain the ESM module scope.
    const [{ default: postcss }, { default: fcssPostcss }] = await Promise.all([
      import('postcss'),
      import('@fcss/postcss'),
    ]);

    const safelistExact =
      config.safelist?.filter((s): s is string => typeof s === 'string') ?? [];
    const safelistPatterns =
      config.safelist
        ?.filter((s): s is FcssSafelistPattern => typeof s === 'object' && 'pattern' in s)
        .map((s) => s.pattern) ?? [];

    const pluginOpts = {
      manifest: manifestPath,
      content,
      cwd: this.dir,
      report: true as const,
      ...(safelistExact.length > 0 || safelistPatterns.length > 0
        ? { safelist: { exact: safelistExact, patterns: safelistPatterns } }
        : {}),
    };

    for (const [assetName, asset] of cssEntries) {
      const raw = asset.source();
      const source = Buffer.isBuffer(raw) ? raw.toString('utf8') : (raw as string);

      if (!isFcssBundle(source)) continue;

      try {
        const result = await postcss([fcssPostcss(pluginOpts)]).process(source, {
          from: assetName,
        });

        const replacement = this.makeSource(result.css);

        const updateAsset = compilation['updateAsset'] as
          | ((name: string, src: WebpackAsset) => void)
          | undefined;

        if (typeof updateAsset === 'function') {
          updateAsset.call(compilation, assetName, replacement);
        } else {
          assets[assetName] = replacement;
        }
      } catch (err) {
        console.warn(`[@fcss/next] Purge failed for "${assetName}": ${String(err)}`);
      }
    }
  }
}

type WebpackConfig = Record<string, unknown>;
type WebpackOptions = {
  dir: string;
  dev: boolean;
  isServer: boolean;
  buildId: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type NextConfig = Record<string, any>;

export function withFcss(nextConfig: NextConfig = {}): NextConfig {
  return {
    ...nextConfig,
    webpack(config: WebpackConfig, options: WebpackOptions) {
      const existingWebpack = nextConfig['webpack'];
      if (typeof existingWebpack === 'function') {
        config = existingWebpack(config, options) as WebpackConfig;
      }

      // Purge only in production. isServer=false targets the browser build,
      // which is where mini-css-extract-plugin extracts global CSS chunks.
      if (!options.dev && !options.isServer) {
        const plugins = config['plugins'] as unknown[];
        plugins.push(new FcssWebpackPlugin(options.dir));
      }

      return config;
    },
  };
}
