// @file packages/generator/src/__tests__/validate-css.test.ts
// @description Unit tests for validateCss.
// @layer tests
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import { describe, it, expect } from 'vitest';
import { validateCss } from '../validate-css.js';

describe('validateCss — valid CSS', () => {
  it('passes for a single well-formed rule', () => {
    expect(() => validateCss('.display--flex { display: flex }')).not.toThrow();
  });

  it('passes for multiple well-formed rules', () => {
    const css = '.display--flex { display: flex }\n.display--none { display: none }';
    expect(() => validateCss(css)).not.toThrow();
  });

  it('passes for generated file header comment', () => {
    const css = '/** Generated by FCSS. */\n.foo { color: red }';
    expect(() => validateCss(css)).not.toThrow();
  });
});

describe('validateCss — duplicate selectors', () => {
  it('throws on duplicate selectors', () => {
    const css = '.foo { display: flex }\n.foo { display: block }';
    expect(() => validateCss(css, 'test')).toThrow(/Duplicate selector/);
  });
});

describe('validateCss — !important', () => {
  it('throws when !important is used', () => {
    const css = '.foo { display: flex !important }';
    expect(() => validateCss(css, 'test')).toThrow(/!important/);
  });
});

describe('validateCss — forbidden patterns', () => {
  it('throws on :has(', () => {
    const css = '.foo:has(.bar) { display: flex }';
    expect(() => validateCss(css, 'test')).toThrow(/Forbidden/);
  });

  it('throws on @layer', () => {
    const css = '@layer base { .foo { display: flex } }';
    expect(() => validateCss(css, 'test')).toThrow(/Forbidden/);
  });

  it('throws on @container', () => {
    expect(() =>
      validateCss('.foo { display: flex } @container (min-width: 300px) { .bar { color: red } }'),
    ).toThrow(/Forbidden/);
  });

  it('throws on oklch(', () => {
    const css = '.foo { color: oklch(50% 0.1 30) }';
    expect(() => validateCss(css, 'test')).toThrow(/Forbidden/);
  });

  it('throws on color-mix(', () => {
    const css = '.foo { color: color-mix(in srgb, red 50%, blue) }';
    expect(() => validateCss(css, 'test')).toThrow(/Forbidden/);
  });
});

describe('validateCss — one declaration per rule', () => {
  it('throws when a rule has zero declarations', () => {
    expect(() => validateCss('.foo {}', 'test')).toThrow(/declaration/);
  });
});
