// @file eslint.config.mjs
// @description ESLint flat configuration for the FCSS monorepo.
// @layer root
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(js.configs.recommended, ...tseslint.configs.recommended, {
  ignores: [
    '**/dist/**',
    '**/dist-schematics/**',
    '**/node_modules/**',
    '**/.next/**',
    '**/out/**',
    'packages/core/src/generated/**',
    // Auto-generated by Next.js — must not be edited or linted
    '**/next-env.d.ts',
    // Auto-generated by Astro — must not be edited or linted
    '**/.astro/**',
    // Legacy docs app — moved without modification per Phase 1 constraints
    'apps/docs/**',
    // Rust crate — linted by cargo clippy, not ESLint
    'packages/zed/**',
  ],
});
