// @file packages/core/tests/css-validation.test.ts
// @description CSS validation tests for @fcss/core generated dist files.
// @layer tests
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.resolve(__dirname, '../dist');

function readDist(name: string): string {
  return fs.readFileSync(path.join(distDir, name), 'utf8');
}

const GENERATED_HEADER = '/**\n * Generated by FCSS.\n * Do not edit this file manually.\n */';

const FORBIDDEN_PATTERNS = [
  ':has(',
  ':is(',
  ':where(',
  '@layer',
  '@container',
  'oklch(',
  'color-mix(',
];

function assertGeneratedHeader(content: string, label: string): void {
  expect(content, `${label} must begin with generated header`).toContain(GENERATED_HEADER);
}

function assertNoForbiddenPatterns(content: string, label: string): void {
  for (const pattern of FORBIDDEN_PATTERNS) {
    expect(content, `${label} must not contain "${pattern}"`).not.toContain(pattern);
  }
}

function assertNoDuplicateSelectors(css: string, label: string): void {
  const selectorRe = /^([^{]+)\s*\{/gm;
  const seen = new Set<string>();
  let m;
  while ((m = selectorRe.exec(css)) !== null) {
    const sel = m[1]?.trim() ?? '';
    if (!sel || sel.startsWith('@') || sel.startsWith('*') || sel === ':root') continue;
    expect(seen.has(sel), `${label}: duplicate selector "${sel}"`).toBe(false);
    seen.add(sel);
  }
}

function assertOneDeclarationPerRule(css: string, label: string): void {
  // Strip block comments before parsing so the generated file header doesn't confuse the regex.
  const cssClean = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const ruleRe = /^([^@{][^{]*)\{([^}]*)\}/gm;
  const skipPrefixes = [':root', '*', 'body', 'img,', 'input,', 'p,', 'p ', 'h1'];
  let m;
  while ((m = ruleRe.exec(cssClean)) !== null) {
    const selector = m[1]?.trim() ?? '';
    const body = m[2] ?? '';
    if (!selector || skipPrefixes.some((p) => selector.startsWith(p))) continue;
    // The generator omits the trailing semicolon on single declarations (valid CSS).
    // Check that there are at most 1 semicolons and exactly 1 colon (the property:value separator).
    const semicolons = (body.match(/;/g) ?? []).length;
    expect(
      semicolons,
      `${label}: rule "${selector.slice(0, 60)}" has too many declarations`,
    ).toBeLessThanOrEqual(1);
    const colonCount = (body.match(/(?<!-):/g) ?? []).length;
    expect(
      colonCount,
      `${label}: rule "${selector.slice(0, 60)}" must have exactly 1 declaration`,
    ).toBeGreaterThanOrEqual(1);
  }
}

function assertNoImportant(css: string, label: string): void {
  const importantRe = /!important/g;
  // Allow !important only in reset.css (which isn't a utility file)
  const matches = css.match(importantRe) ?? [];
  expect(matches.length, `${label} must not contain !important`).toBe(0);
}

describe('dist/ files exist', () => {
  const required = [
    'utilities.css',
    'full.css',
    'reset.css',
    'root.css',
    'states.css',
    'states/pseudo.css',
    'states/aria.css',
    'breakpoints.css',
    'breakpoints/sm.css',
    'breakpoints/md.css',
    'breakpoints/lg.css',
    'breakpoints/xl.css',
    'breakpoints/xxl.css',
    'manifest.json',
    'statistics.json',
  ];

  for (const file of required) {
    it(`${file} exists`, () => {
      expect(fs.existsSync(path.join(distDir, file))).toBe(true);
    });
  }
});

describe('utilities.css', () => {
  const css = readDist('utilities.css');

  it('begins with generated header', () => assertGeneratedHeader(css, 'utilities.css'));
  it('no forbidden CSS patterns', () => assertNoForbiddenPatterns(css, 'utilities.css'));
  it('no duplicate selectors', () => assertNoDuplicateSelectors(css, 'utilities.css'));
  it('one declaration per rule', () => assertOneDeclarationPerRule(css, 'utilities.css'));
  it('no !important', () => assertNoImportant(css, 'utilities.css'));
  it('has non-trivial content', () => expect(css.length).toBeGreaterThan(1000));
});

describe('reset.css', () => {
  const css = readDist('reset.css');

  it('begins with generated header', () => assertGeneratedHeader(css, 'reset.css'));
  it('no forbidden CSS patterns', () => assertNoForbiddenPatterns(css, 'reset.css'));
  it('contains box-sizing rule', () => expect(css).toContain('box-sizing'));
});

describe('root.css', () => {
  const css = readDist('root.css');

  it('begins with generated header', () => assertGeneratedHeader(css, 'root.css'));
  it('contains :root block', () => expect(css).toContain(':root'));
  it('declares --fcss-color-black', () => expect(css).toContain('--fcss-color-black'));
  it('declares --fcss-color-blue', () => expect(css).toContain('--fcss-color-blue'));
  it('declares --fcss-color-white', () => expect(css).toContain('--fcss-color-white'));
  it('contains deprecated legacy aliases', () => expect(css).toContain('@deprecated'));
  it('legacy --black alias present', () =>
    expect(css).toContain('--black: var(--fcss-color-black)'));
});

describe('states/pseudo.css', () => {
  const css = readDist('states/pseudo.css');

  it('begins with generated header', () => assertGeneratedHeader(css, 'states/pseudo.css'));
  it('no forbidden CSS patterns', () => assertNoForbiddenPatterns(css, 'states/pseudo.css'));
  it('no !important', () => assertNoImportant(css, 'states/pseudo.css'));
});

describe('breakpoints/sm.css', () => {
  const css = readDist('breakpoints/sm.css');

  it('begins with generated header', () => assertGeneratedHeader(css, 'breakpoints/sm.css'));
  it('contains @media (min-width: 576px)', () =>
    expect(css).toContain('@media (min-width: 576px)'));
  it('no forbidden CSS patterns', () => assertNoForbiddenPatterns(css, 'breakpoints/sm.css'));
});

describe('manifest.json', () => {
  it('is valid JSON', () => {
    const raw = fs.readFileSync(path.join(distDir, 'manifest.json'), 'utf8');
    expect(() => JSON.parse(raw)).not.toThrow();
  });

  it('is a non-empty array', () => {
    const raw = fs.readFileSync(path.join(distDir, 'manifest.json'), 'utf8');
    const manifest = JSON.parse(raw) as unknown[];
    expect(Array.isArray(manifest)).toBe(true);
    expect(manifest.length).toBeGreaterThan(0);
  });

  it('entries have required fields', () => {
    const raw = fs.readFileSync(path.join(distDir, 'manifest.json'), 'utf8');
    const manifest = JSON.parse(raw) as Record<string, unknown>[];
    const sample = manifest.slice(0, 10);
    for (const entry of sample) {
      expect(typeof entry['className']).toBe('string');
      expect(typeof entry['selector']).toBe('string');
      expect(typeof entry['property']).toBe('string');
      expect(typeof entry['value']).toBe('string');
      expect(typeof entry['category']).toBe('string');
    }
  });

  it('first entry selector starts with .', () => {
    const raw = fs.readFileSync(path.join(distDir, 'manifest.json'), 'utf8');
    const manifest = JSON.parse(raw) as Record<string, unknown>[];
    const first = manifest[0];
    const selector = first?.['selector'];
    expect(typeof selector).toBe('string');
    expect((selector as string).startsWith('.')).toBe(true);
  });
});

describe('statistics.json', () => {
  it('is valid JSON with expected fields', () => {
    const raw = fs.readFileSync(path.join(distDir, 'statistics.json'), 'utf8');
    const stats = JSON.parse(raw) as Record<string, unknown>;
    expect(typeof stats['utilities']).toBe('number');
    expect(typeof stats['baseUtilities']).toBe('number');
    expect(typeof stats['rawBytes']).toBe('number');
    expect(typeof stats['gzipBytes']).toBe('number');
    expect(stats['utilities'] as number).toBeGreaterThan(1000);
  });
});

describe('full.css', () => {
  it('begins with generated header', () => {
    const css = readDist('full.css');
    assertGeneratedHeader(css, 'full.css');
  });

  it('contains :root block (root.css content)', () => {
    const css = readDist('full.css');
    expect(css).toContain(':root');
  });

  it('contains box-sizing reset', () => {
    const css = readDist('full.css');
    expect(css).toContain('box-sizing');
  });

  it('no forbidden CSS patterns', () => {
    const css = readDist('full.css');
    assertNoForbiddenPatterns(css, 'full.css');
  });
});

describe('generation determinism', () => {
  it('manifest.json is consistent with dist/utilities.css class names', () => {
    const raw = fs.readFileSync(path.join(distDir, 'manifest.json'), 'utf8');
    const manifest = JSON.parse(raw) as Record<string, unknown>[];
    const utilitiesCss = readDist('utilities.css');

    // Each manifest entry with no breakpoint/condition should appear in utilities.css
    const baseEntries = manifest.filter(
      (e) => e['breakpoint'] === undefined && e['condition'] === undefined,
    );
    const sample = baseEntries.slice(0, 5);
    for (const entry of sample) {
      const sel = entry['selector'] as string;
      expect(utilitiesCss, `utilities.css should contain selector "${sel}"`).toContain(sel);
    }
  });
});
