// @file packages/spec/src/properties/alignment.ts
// @description Box alignment properties shared between flex and grid (CSS Box Alignment Level 3).
// @layer domain
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import type { FcssPropertyDefinition } from '../types.js';
import { PC_NONE } from '../states/pseudo-classes.js';
import { SUPPORTED_ARIA_STATES } from '../states/aria.js';

const ARIA = SUPPORTED_ARIA_STATES;

const CONTENT_DISTRIBUTION = [
  { classValue: 'normal', cssValue: 'normal' },
  { classValue: 'stretch', cssValue: 'stretch' },
  { classValue: 'center', cssValue: 'center' },
  { classValue: 'start', cssValue: 'start' },
  { classValue: 'end', cssValue: 'end' },
  { classValue: 'flex-start', cssValue: 'flex-start' },
  { classValue: 'flex-end', cssValue: 'flex-end' },
  { classValue: 'space-between', cssValue: 'space-between' },
  { classValue: 'space-around', cssValue: 'space-around' },
  { classValue: 'space-evenly', cssValue: 'space-evenly' },
  { classValue: 'baseline', cssValue: 'baseline' },
  { classValue: 'first-baseline', cssValue: 'first baseline' },
  { classValue: 'last-baseline', cssValue: 'last baseline' },
];

const SELF_ALIGNMENT = [
  { classValue: 'auto', cssValue: 'auto' },
  { classValue: 'normal', cssValue: 'normal' },
  { classValue: 'stretch', cssValue: 'stretch' },
  { classValue: 'center', cssValue: 'center' },
  { classValue: 'start', cssValue: 'start' },
  { classValue: 'end', cssValue: 'end' },
  { classValue: 'flex-start', cssValue: 'flex-start' },
  { classValue: 'flex-end', cssValue: 'flex-end' },
  { classValue: 'baseline', cssValue: 'baseline' },
];

const ITEMS_ALIGNMENT = [
  { classValue: 'normal', cssValue: 'normal' },
  { classValue: 'stretch', cssValue: 'stretch' },
  { classValue: 'center', cssValue: 'center' },
  { classValue: 'start', cssValue: 'start' },
  { classValue: 'end', cssValue: 'end' },
  { classValue: 'flex-start', cssValue: 'flex-start' },
  { classValue: 'flex-end', cssValue: 'flex-end' },
  { classValue: 'baseline', cssValue: 'baseline' },
];

const JUSTIFY_CONTENT = [
  { classValue: 'normal', cssValue: 'normal' },
  { classValue: 'center', cssValue: 'center' },
  { classValue: 'start', cssValue: 'start' },
  { classValue: 'end', cssValue: 'end' },
  { classValue: 'flex-start', cssValue: 'flex-start' },
  { classValue: 'flex-end', cssValue: 'flex-end' },
  { classValue: 'space-between', cssValue: 'space-between' },
  { classValue: 'space-around', cssValue: 'space-around' },
  { classValue: 'space-evenly', cssValue: 'space-evenly' },
  { classValue: 'stretch', cssValue: 'stretch' },
  { classValue: 'safe-center', cssValue: 'safe center' },
  { classValue: 'unsafe-center', cssValue: 'unsafe center' },
];

export const ALIGNMENT_PROPERTIES: readonly FcssPropertyDefinition[] = [
  {
    property: 'justify-content',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: JUSTIFY_CONTENT,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'align-items',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: ITEMS_ALIGNMENT,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'align-content',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: CONTENT_DISTRIBUTION,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'align-self',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: SELF_ALIGNMENT,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'justify-items',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: [{ classValue: 'auto', cssValue: 'auto' }, ...ITEMS_ALIGNMENT],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'justify-self',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: SELF_ALIGNMENT,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'place-items',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'preset-only',
    values: [
      { classValue: 'center', cssValue: 'center' },
      { classValue: 'start', cssValue: 'start' },
      { classValue: 'end', cssValue: 'end' },
      { classValue: 'stretch', cssValue: 'stretch' },
      { classValue: 'center-start', cssValue: 'center start' },
      { classValue: 'center-end', cssValue: 'center end' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'place-self',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'preset-only',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'center', cssValue: 'center' },
      { classValue: 'start', cssValue: 'start' },
      { classValue: 'end', cssValue: 'end' },
      { classValue: 'stretch', cssValue: 'stretch' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'gap',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'row-gap',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: [{ classValue: 'normal', cssValue: 'normal' }],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'column-gap',
    category: 'alignment',
    specification: 'CSS Box Alignment Level 3',
    status: 'supported',
    values: [{ classValue: 'normal', cssValue: 'normal' }],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'order',
    category: 'alignment',
    specification: 'CSS Flexible Box Layout Level 1',
    status: 'supported',
    values: [{ classValue: '0', cssValue: '0' }],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'integer',
  },
];
