// @file packages/spec/src/properties/box-model.ts
// @description Box model properties: margin, padding, border, border-radius, box-shadow.
// @layer domain
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import type { FcssPropertyDefinition } from '../types.js';
import { PC_INTERACTION, PC_NONE } from '../states/pseudo-classes.js';
import { SUPPORTED_ARIA_STATES } from '../states/aria.js';
import { FCSS_COLOR_VALUES } from '../values/colors.js';

const ARIA = SUPPORTED_ARIA_STATES;

const MARGIN_KEYWORDS = [
  { classValue: 'auto', cssValue: 'auto' },
];

const BORDER_STYLE_VALUES = [
  { classValue: 'none', cssValue: 'none' },
  { classValue: 'hidden', cssValue: 'hidden' },
  { classValue: 'dotted', cssValue: 'dotted' },
  { classValue: 'dashed', cssValue: 'dashed' },
  { classValue: 'solid', cssValue: 'solid' },
  { classValue: 'double', cssValue: 'double' },
  { classValue: 'groove', cssValue: 'groove' },
  { classValue: 'ridge', cssValue: 'ridge' },
  { classValue: 'inset', cssValue: 'inset' },
  { classValue: 'outset', cssValue: 'outset' },
];

const BORDER_WIDTH_KEYWORDS = [
  { classValue: 'thin', cssValue: 'thin' },
  { classValue: 'medium', cssValue: 'medium' },
  { classValue: 'thick', cssValue: 'thick' },
];

const BOX_SHADOW_PRESETS = [
  { classValue: 'none', cssValue: 'none' },
  { classValue: 'sm', cssValue: '0 1px 2px 0 rgb(0 0 0 / 0.05)' },
  { classValue: 'md', cssValue: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)' },
  { classValue: 'lg', cssValue: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)' },
  { classValue: 'xl', cssValue: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)' },
  { classValue: 'inner', cssValue: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)' },
];

export const BOX_MODEL_PROPERTIES: readonly FcssPropertyDefinition[] = [
  // margin longhands
  {
    property: 'margin-top',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'margin-right',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'margin-bottom',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'margin-left',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'margin',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  // padding longhands
  {
    property: 'padding-top',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'padding-right',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'padding-bottom',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'padding-left',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'padding',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  // border-width longhands
  {
    property: 'border-top-width',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_WIDTH_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'border-right-width',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_WIDTH_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'border-bottom-width',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_WIDTH_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'border-left-width',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_WIDTH_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'border-width',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'preset-only',
    values: BORDER_WIDTH_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  // border-style longhands
  {
    property: 'border-top-style',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_STYLE_VALUES,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-right-style',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_STYLE_VALUES,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-bottom-style',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_STYLE_VALUES,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-left-style',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: BORDER_STYLE_VALUES,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-style',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'preset-only',
    values: BORDER_STYLE_VALUES,
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  // border-color longhands
  {
    property: 'border-top-color',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [...FCSS_COLOR_VALUES],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-right-color',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [...FCSS_COLOR_VALUES],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-bottom-color',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [...FCSS_COLOR_VALUES],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-left-color',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'supported',
    values: [...FCSS_COLOR_VALUES],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'border-color',
    category: 'box-model',
    specification: 'CSS2.1',
    status: 'preset-only',
    values: [...FCSS_COLOR_VALUES],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  // border-radius
  {
    property: 'border-top-left-radius',
    category: 'box-model',
    specification: 'CSS Backgrounds and Borders Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'border-top-right-radius',
    category: 'box-model',
    specification: 'CSS Backgrounds and Borders Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'border-bottom-right-radius',
    category: 'box-model',
    specification: 'CSS Backgrounds and Borders Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'border-bottom-left-radius',
    category: 'box-model',
    specification: 'CSS Backgrounds and Borders Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'border-radius',
    category: 'box-model',
    specification: 'CSS Backgrounds and Borders Level 3',
    status: 'supported',
    values: [
      { classValue: 'full', cssValue: '9999px' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  // box-shadow
  {
    property: 'box-shadow',
    category: 'box-model',
    specification: 'CSS Backgrounds and Borders Level 3',
    status: 'preset-only',
    values: BOX_SHADOW_PRESETS,
    supportsResponsive: false,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  // logical property variants (experimental — CSS Logical Properties Level 1)
  {
    property: 'margin-block',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use margin-top/margin-bottom for the CSS3 equivalent',
  },
  {
    property: 'margin-block-start',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use margin-top for the CSS3 equivalent',
  },
  {
    property: 'margin-block-end',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use margin-bottom for the CSS3 equivalent',
  },
  {
    property: 'margin-inline',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use margin-left/margin-right for the CSS3 equivalent',
  },
  {
    property: 'margin-inline-start',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use margin-left for LTR equivalent',
  },
  {
    property: 'margin-inline-end',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: MARGIN_KEYWORDS,
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use margin-right for LTR equivalent',
  },
  {
    property: 'padding-block',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use padding-top/padding-bottom for the CSS3 equivalent',
  },
  {
    property: 'padding-inline',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use padding-left/padding-right for the CSS3 equivalent',
  },
  {
    property: 'padding-inline-start',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use padding-left for LTR equivalent',
  },
  {
    property: 'padding-inline-end',
    category: 'box-model',
    specification: 'CSS Logical Properties Level 1',
    status: 'experimental',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
    notes: 'CSS Logical Properties — outside the CSS3 profile; use padding-right for LTR equivalent',
  },
];
