// @file packages/spec/src/properties/display.ts
// @description Display, visibility, overflow, box-sizing, float, clear, resize, and object properties.
// @layer domain
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import type { FcssPropertyDefinition } from '../types.js';
import { PC_INTERACTION, PC_NONE } from '../states/pseudo-classes.js';
import { SUPPORTED_ARIA_STATES } from '../states/aria.js';

const ARIA = SUPPORTED_ARIA_STATES;

export const DISPLAY_PROPERTIES: readonly FcssPropertyDefinition[] = [
  {
    property: 'display',
    category: 'display',
    specification: 'CSS2.1 / CSS Display Level 3',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'block', cssValue: 'block' },
      { classValue: 'inline', cssValue: 'inline' },
      { classValue: 'inline-block', cssValue: 'inline-block' },
      { classValue: 'flex', cssValue: 'flex' },
      { classValue: 'inline-flex', cssValue: 'inline-flex' },
      { classValue: 'grid', cssValue: 'grid' },
      { classValue: 'inline-grid', cssValue: 'inline-grid' },
      { classValue: 'table', cssValue: 'table' },
      { classValue: 'table-cell', cssValue: 'table-cell' },
      { classValue: 'table-row', cssValue: 'table-row' },
      { classValue: 'table-caption', cssValue: 'table-caption' },
      { classValue: 'table-column', cssValue: 'table-column' },
      { classValue: 'table-column-group', cssValue: 'table-column-group' },
      { classValue: 'table-footer-group', cssValue: 'table-footer-group' },
      { classValue: 'table-header-group', cssValue: 'table-header-group' },
      { classValue: 'table-row-group', cssValue: 'table-row-group' },
      { classValue: 'list-item', cssValue: 'list-item' },
      { classValue: 'contents', cssValue: 'contents' },
      { classValue: 'flow-root', cssValue: 'flow-root' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'visibility',
    category: 'display',
    specification: 'CSS2.1',
    status: 'supported',
    values: [
      { classValue: 'visible', cssValue: 'visible' },
      { classValue: 'hidden', cssValue: 'hidden' },
      { classValue: 'collapse', cssValue: 'collapse' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'overflow',
    category: 'display',
    specification: 'CSS2.1 / CSS Overflow Level 3',
    status: 'supported',
    values: [
      { classValue: 'visible', cssValue: 'visible' },
      { classValue: 'hidden', cssValue: 'hidden' },
      { classValue: 'scroll', cssValue: 'scroll' },
      { classValue: 'auto', cssValue: 'auto' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'overflow-x',
    category: 'display',
    specification: 'CSS Overflow Level 3',
    status: 'supported',
    values: [
      { classValue: 'visible', cssValue: 'visible' },
      { classValue: 'hidden', cssValue: 'hidden' },
      { classValue: 'scroll', cssValue: 'scroll' },
      { classValue: 'auto', cssValue: 'auto' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'overflow-y',
    category: 'display',
    specification: 'CSS Overflow Level 3',
    status: 'supported',
    values: [
      { classValue: 'visible', cssValue: 'visible' },
      { classValue: 'hidden', cssValue: 'hidden' },
      { classValue: 'scroll', cssValue: 'scroll' },
      { classValue: 'auto', cssValue: 'auto' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'box-sizing',
    category: 'display',
    specification: 'CSS Box Model Level 3',
    status: 'supported',
    values: [
      { classValue: 'content-box', cssValue: 'content-box' },
      { classValue: 'border-box', cssValue: 'border-box' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'float',
    category: 'display',
    specification: 'CSS2.1',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'left', cssValue: 'left' },
      { classValue: 'right', cssValue: 'right' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'clear',
    category: 'display',
    specification: 'CSS2.1',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'left', cssValue: 'left' },
      { classValue: 'right', cssValue: 'right' },
      { classValue: 'both', cssValue: 'both' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'resize',
    category: 'display',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'both', cssValue: 'both' },
      { classValue: 'horizontal', cssValue: 'horizontal' },
      { classValue: 'vertical', cssValue: 'vertical' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'object-fit',
    category: 'display',
    specification: 'CSS Images Level 3',
    status: 'supported',
    values: [
      { classValue: 'fill', cssValue: 'fill' },
      { classValue: 'contain', cssValue: 'contain' },
      { classValue: 'cover', cssValue: 'cover' },
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'scale-down', cssValue: 'scale-down' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'object-position',
    category: 'display',
    specification: 'CSS Images Level 3',
    status: 'preset-only',
    values: [
      { classValue: 'center', cssValue: 'center' },
      { classValue: 'top', cssValue: 'top' },
      { classValue: 'bottom', cssValue: 'bottom' },
      { classValue: 'left', cssValue: 'left' },
      { classValue: 'right', cssValue: 'right' },
      { classValue: 'top-left', cssValue: 'top left' },
      { classValue: 'top-right', cssValue: 'top right' },
      { classValue: 'bottom-left', cssValue: 'bottom left' },
      { classValue: 'bottom-right', cssValue: 'bottom right' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
];
