// @file packages/spec/src/properties/typography.ts
// @description Typography properties: font, text, spacing, and writing-mode.
// @layer domain
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import type { FcssPropertyDefinition } from '../types.js';
import { PC_INTERACTION, PC_WITH_LINK, PC_NONE } from '../states/pseudo-classes.js';
import { SUPPORTED_ARIA_STATES } from '../states/aria.js';

const ARIA = SUPPORTED_ARIA_STATES;

export const TYPOGRAPHY_PROPERTIES: readonly FcssPropertyDefinition[] = [
  {
    property: 'font-family',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'supported',
    values: [
      {
        classValue: 'sans-serif',
        cssValue: 'var(--fcss-font-family-sans-serif)',
        legacyAliases: ['var(--font-family-sans-serif)'],
      },
      {
        classValue: 'serif',
        cssValue: 'var(--fcss-font-family-serif)',
        legacyAliases: ['var(--font-family-serif)'],
      },
      {
        classValue: 'mono',
        cssValue: 'var(--fcss-font-family-mono)',
        legacyAliases: ['var(--font-family-mono)'],
      },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'font-size',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'supported',
    values: [
      { classValue: 'xs', cssValue: '0.75rem' },
      { classValue: 'sm', cssValue: '0.875rem' },
      { classValue: 'base', cssValue: '1rem' },
      { classValue: 'lg', cssValue: '1.125rem' },
      { classValue: 'xl', cssValue: '1.25rem' },
      { classValue: '2xl', cssValue: '1.5rem' },
      { classValue: '3xl', cssValue: '1.875rem' },
      { classValue: '4xl', cssValue: '2.25rem' },
      { classValue: '5xl', cssValue: '3rem' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length-percentage',
  },
  {
    property: 'font-style',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'italic', cssValue: 'italic' },
      { classValue: 'oblique', cssValue: 'oblique' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'font-weight',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'bold', cssValue: 'bold' },
      { classValue: 'bolder', cssValue: 'bolder' },
      { classValue: 'lighter', cssValue: 'lighter' },
      { classValue: '100', cssValue: '100' },
      { classValue: '200', cssValue: '200' },
      { classValue: '300', cssValue: '300' },
      { classValue: '400', cssValue: '400' },
      { classValue: '500', cssValue: '500' },
      { classValue: '600', cssValue: '600' },
      { classValue: '700', cssValue: '700' },
      { classValue: '800', cssValue: '800' },
      { classValue: '900', cssValue: '900' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'font-stretch',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'condensed', cssValue: 'condensed' },
      { classValue: 'semi-condensed', cssValue: 'semi-condensed' },
      { classValue: 'extra-condensed', cssValue: 'extra-condensed' },
      { classValue: 'ultra-condensed', cssValue: 'ultra-condensed' },
      { classValue: 'expanded', cssValue: 'expanded' },
      { classValue: 'semi-expanded', cssValue: 'semi-expanded' },
      { classValue: 'extra-expanded', cssValue: 'extra-expanded' },
      { classValue: 'ultra-expanded', cssValue: 'ultra-expanded' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'font-variant',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'small-caps', cssValue: 'small-caps' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'line-height',
    category: 'typography',
    specification: 'CSS2.1',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'none', cssValue: '1' },
      { classValue: 'tight', cssValue: '1.25' },
      { classValue: 'snug', cssValue: '1.375' },
      { classValue: 'relaxed', cssValue: '1.625' },
      { classValue: 'loose', cssValue: '2' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'number',
  },
  {
    property: 'letter-spacing',
    category: 'typography',
    specification: 'CSS2.1',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'word-spacing',
    category: 'typography',
    specification: 'CSS2.1',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'text-align',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'supported',
    values: [
      { classValue: 'left', cssValue: 'left' },
      { classValue: 'right', cssValue: 'right' },
      { classValue: 'center', cssValue: 'center' },
      { classValue: 'justify', cssValue: 'justify' },
      { classValue: 'start', cssValue: 'start' },
      { classValue: 'end', cssValue: 'end' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'text-indent',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    numericBehavior: 'length-percentage',
  },
  {
    property: 'text-transform',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'capitalize', cssValue: 'capitalize' },
      { classValue: 'uppercase', cssValue: 'uppercase' },
      { classValue: 'lowercase', cssValue: 'lowercase' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'text-decoration-line',
    category: 'typography',
    specification: 'CSS Text Decoration Level 3',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'underline', cssValue: 'underline' },
      { classValue: 'overline', cssValue: 'overline' },
      { classValue: 'line-through', cssValue: 'line-through' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_WITH_LINK,
    supportedAriaStates: ARIA,
  },
  {
    property: 'text-decoration-style',
    category: 'typography',
    specification: 'CSS Text Decoration Level 3',
    status: 'supported',
    values: [
      { classValue: 'solid', cssValue: 'solid' },
      { classValue: 'double', cssValue: 'double' },
      { classValue: 'dotted', cssValue: 'dotted' },
      { classValue: 'dashed', cssValue: 'dashed' },
      { classValue: 'wavy', cssValue: 'wavy' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_WITH_LINK,
    supportedAriaStates: ARIA,
  },
  {
    property: 'text-decoration-color',
    category: 'typography',
    specification: 'CSS Text Decoration Level 3',
    status: 'preset-only',
    values: [
      { classValue: 'currentColor', cssValue: 'currentColor' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_WITH_LINK,
    supportedAriaStates: ARIA,
  },
  {
    property: 'text-decoration',
    category: 'typography',
    specification: 'CSS Text Decoration Level 3',
    status: 'preset-only',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'underline', cssValue: 'underline' },
      { classValue: 'line-through', cssValue: 'line-through' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_WITH_LINK,
    supportedAriaStates: ARIA,
  },
  {
    property: 'text-overflow',
    category: 'typography',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [
      { classValue: 'clip', cssValue: 'clip' },
      { classValue: 'ellipsis', cssValue: 'ellipsis' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'white-space',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'nowrap', cssValue: 'nowrap' },
      { classValue: 'pre', cssValue: 'pre' },
      { classValue: 'pre-wrap', cssValue: 'pre-wrap' },
      { classValue: 'pre-line', cssValue: 'pre-line' },
      { classValue: 'break-spaces', cssValue: 'break-spaces' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'word-break',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'break-all', cssValue: 'break-all' },
      { classValue: 'keep-all', cssValue: 'keep-all' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'overflow-wrap',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'supported',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'break-word', cssValue: 'break-word' },
      { classValue: 'anywhere', cssValue: 'anywhere' },
    ],
    supportsResponsive: true,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'direction',
    category: 'typography',
    specification: 'CSS Writing Modes Level 3',
    status: 'supported',
    values: [
      { classValue: 'ltr', cssValue: 'ltr' },
      { classValue: 'rtl', cssValue: 'rtl' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'writing-mode',
    category: 'typography',
    specification: 'CSS Writing Modes Level 3',
    status: 'supported',
    values: [
      { classValue: 'horizontal-tb', cssValue: 'horizontal-tb' },
      { classValue: 'vertical-rl', cssValue: 'vertical-rl' },
      { classValue: 'vertical-lr', cssValue: 'vertical-lr' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  // experimental legacy typography properties
  {
    property: 'font-kerning',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'experimental',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'none', cssValue: 'none' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes: 'CSS Fonts Level 3 feature; supported in modern browsers but outside the base CSS3 profile',
  },
  {
    property: 'font-optical-sizing',
    category: 'typography',
    specification: 'CSS Fonts Level 4',
    status: 'experimental',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'none', cssValue: 'none' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes: 'CSS Fonts Level 4 (variable fonts) — outside the CSS3 profile',
  },
  {
    property: 'font-variant-caps',
    category: 'typography',
    specification: 'CSS Fonts Level 3',
    status: 'experimental',
    values: [
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'small-caps', cssValue: 'small-caps' },
      { classValue: 'all-small-caps', cssValue: 'all-small-caps' },
      { classValue: 'petite-caps', cssValue: 'petite-caps' },
      { classValue: 'unicase', cssValue: 'unicase' },
      { classValue: 'titling-caps', cssValue: 'titling-caps' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes: 'CSS Fonts Level 3 longhand for font-variant; use font-variant for the CSS3 shorthand equivalent',
  },
  {
    property: 'hanging-punctuation',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'experimental',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'first', cssValue: 'first' },
      { classValue: 'last', cssValue: 'last' },
      { classValue: 'allow-end', cssValue: 'allow-end' },
      { classValue: 'force-end', cssValue: 'force-end' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes: 'CSS Text Level 3 feature with limited browser support; outside core CSS3 profile',
  },
  {
    property: 'line-break',
    category: 'typography',
    specification: 'CSS Text Level 3',
    status: 'experimental',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'loose', cssValue: 'loose' },
      { classValue: 'normal', cssValue: 'normal' },
      { classValue: 'strict', cssValue: 'strict' },
      { classValue: 'anywhere', cssValue: 'anywhere' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes: 'Primarily relevant for CJK text; limited utility in most FCSS contexts',
  },
];
