// @file packages/spec/src/properties/ui.ts
// @description UI and pointer properties: cursor, pointer-events, user-select, appearance, caret-color, outline.
// @layer domain
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import type { FcssPropertyDefinition } from '../types.js';
import { PC_INTERACTION, PC_FORM, PC_NONE } from '../states/pseudo-classes.js';
import { SUPPORTED_ARIA_STATES } from '../states/aria.js';
import { FCSS_COLOR_VALUES } from '../values/colors.js';

const ARIA = SUPPORTED_ARIA_STATES;

const OUTLINE_STYLE_VALUES = [
  { classValue: 'none', cssValue: 'none' },
  { classValue: 'hidden', cssValue: 'hidden' },
  { classValue: 'dotted', cssValue: 'dotted' },
  { classValue: 'dashed', cssValue: 'dashed' },
  { classValue: 'solid', cssValue: 'solid' },
  { classValue: 'double', cssValue: 'double' },
  { classValue: 'groove', cssValue: 'groove' },
  { classValue: 'ridge', cssValue: 'ridge' },
  { classValue: 'inset', cssValue: 'inset' },
  { classValue: 'outset', cssValue: 'outset' },
];

export const UI_PROPERTIES: readonly FcssPropertyDefinition[] = [
  {
    property: 'cursor',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'default', cssValue: 'default' },
      { classValue: 'pointer', cssValue: 'pointer' },
      { classValue: 'wait', cssValue: 'wait' },
      { classValue: 'text', cssValue: 'text' },
      { classValue: 'move', cssValue: 'move' },
      { classValue: 'help', cssValue: 'help' },
      { classValue: 'not-allowed', cssValue: 'not-allowed' },
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'context-menu', cssValue: 'context-menu' },
      { classValue: 'progress', cssValue: 'progress' },
      { classValue: 'cell', cssValue: 'cell' },
      { classValue: 'crosshair', cssValue: 'crosshair' },
      { classValue: 'vertical-text', cssValue: 'vertical-text' },
      { classValue: 'alias', cssValue: 'alias' },
      { classValue: 'copy', cssValue: 'copy' },
      { classValue: 'no-drop', cssValue: 'no-drop' },
      { classValue: 'grab', cssValue: 'grab' },
      { classValue: 'grabbing', cssValue: 'grabbing' },
      { classValue: 'all-scroll', cssValue: 'all-scroll' },
      { classValue: 'col-resize', cssValue: 'col-resize' },
      { classValue: 'row-resize', cssValue: 'row-resize' },
      { classValue: 'n-resize', cssValue: 'n-resize' },
      { classValue: 'e-resize', cssValue: 'e-resize' },
      { classValue: 's-resize', cssValue: 's-resize' },
      { classValue: 'w-resize', cssValue: 'w-resize' },
      { classValue: 'ne-resize', cssValue: 'ne-resize' },
      { classValue: 'nw-resize', cssValue: 'nw-resize' },
      { classValue: 'se-resize', cssValue: 'se-resize' },
      { classValue: 'sw-resize', cssValue: 'sw-resize' },
      { classValue: 'ew-resize', cssValue: 'ew-resize' },
      { classValue: 'ns-resize', cssValue: 'ns-resize' },
      { classValue: 'nesw-resize', cssValue: 'nesw-resize' },
      { classValue: 'nwse-resize', cssValue: 'nwse-resize' },
      { classValue: 'zoom-in', cssValue: 'zoom-in' },
      { classValue: 'zoom-out', cssValue: 'zoom-out' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'pointer-events',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3 / SVG',
    status: 'supported',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'none', cssValue: 'none' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: ARIA,
  },
  {
    property: 'user-select',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 4',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'text', cssValue: 'text' },
      { classValue: 'all', cssValue: 'all' },
      { classValue: 'contain', cssValue: 'contain' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
  },
  {
    property: 'appearance',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 4',
    status: 'supported',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'auto', cssValue: 'auto' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_FORM,
    supportedAriaStates: ARIA,
  },
  {
    property: 'caret-color',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [{ classValue: 'auto', cssValue: 'auto' }, ...FCSS_COLOR_VALUES],
    supportsResponsive: false,
    supportedPseudoClasses: PC_FORM,
    supportedAriaStates: ARIA,
  },
  {
    property: 'outline-width',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [
      { classValue: 'thin', cssValue: 'thin' },
      { classValue: 'medium', cssValue: 'medium' },
      { classValue: 'thick', cssValue: 'thick' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  {
    property: 'outline-style',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: OUTLINE_STYLE_VALUES,
    supportsResponsive: false,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'outline-color',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [{ classValue: 'invert', cssValue: 'invert' }, ...FCSS_COLOR_VALUES],
    supportsResponsive: false,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
  },
  {
    property: 'outline-offset',
    category: 'ui',
    specification: 'CSS Basic User Interface Level 3',
    status: 'supported',
    values: [],
    supportsResponsive: false,
    supportedPseudoClasses: PC_INTERACTION,
    supportedAriaStates: ARIA,
    numericBehavior: 'length',
  },
  // experimental legacy UI properties
  {
    property: 'image-rendering',
    category: 'ui',
    specification: 'CSS Images Level 3',
    status: 'experimental',
    values: [
      { classValue: 'auto', cssValue: 'auto' },
      { classValue: 'crisp-edges', cssValue: 'crisp-edges' },
      { classValue: 'pixelated', cssValue: 'pixelated' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes:
      'CSS Images Level 3 — limited and inconsistent browser support; outside core CSS3 profile',
  },
  {
    property: 'image-orientation',
    category: 'ui',
    specification: 'CSS Images Level 3',
    status: 'experimental',
    values: [
      { classValue: 'none', cssValue: 'none' },
      { classValue: 'from-image', cssValue: 'from-image' },
    ],
    supportsResponsive: false,
    supportedPseudoClasses: PC_NONE,
    supportedAriaStates: [],
    notes: 'CSS Images Level 3 — EXIF-based image orientation; outside core CSS3 profile',
  },
];
