// @file packages/vite/src/index.ts
// @description FCSS Vite plugin — source scanning, production purge, and dev diagnostics.
// @layer adapters
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import type { Plugin, ResolvedConfig } from 'vite';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as url from 'node:url';

export interface FcssSafelistPattern {
  pattern: RegExp;
}

export interface FcssViteConfig {
  content?: string[];
  safelist?: Array<string | FcssSafelistPattern>;
}

export interface FcssPluginOptions {
  config?: FcssViteConfig;
}

const CONFIG_FILENAMES = [
  'fcss.config.ts',
  'fcss.config.js',
  'fcss.config.mjs',
  'fcss.config.cjs',
] as const;

const DEFAULT_CONTENT = ['src/**/*.{html,js,jsx,ts,tsx}', '!node_modules/**', '!dist/**'];

export async function loadFcssConfig(
  root: string,
): Promise<{ config: FcssViteConfig; configPath: string }> {
  for (const filename of CONFIG_FILENAMES) {
    const configPath = path.join(root, filename);
    if (!fs.existsSync(configPath)) continue;

    let raw: unknown;
    if (path.extname(configPath) === '.ts') {
      const { createJiti } = await import('jiti');
      const jiti = createJiti(configPath, { moduleCache: false });
      raw = await jiti.import(configPath, { default: true });
    } else {
      const mod = (await import(url.pathToFileURL(configPath).href)) as Record<string, unknown>;
      raw = mod['default'] ?? mod;
    }

    return { config: (raw as FcssViteConfig) ?? {}, configPath };
  }
  return { config: {}, configPath: '' };
}

export function resolveManifestPath(root: string): string {
  // Walk up up to 5 levels to handle hoisted node_modules in pnpm workspaces.
  let dir = root;
  for (let i = 0; i < 6; i++) {
    const candidate = path.join(dir, 'node_modules/@fcss/core/dist/manifest.json');
    if (fs.existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(
    '[@fcss/vite] Cannot find FCSS manifest. Install @fcss/core as a project dependency.',
  );
}

export function collectDynamicWarnings(
  source: string,
  filePath: string,
): Array<{ file: string; line: number; fragment: string }> {
  const warnings: Array<{ file: string; line: number; fragment: string }> = [];
  const dynamicRe = /className\s*=\s*\{`[^`]*\$\{[^`]*`\}/g;
  let m: RegExpExecArray | null;
  dynamicRe.lastIndex = 0;
  while ((m = dynamicRe.exec(source)) !== null) {
    const line = source.slice(0, m.index).split('\n').length;
    warnings.push({ file: filePath, line, fragment: m[0].slice(0, 120) });
  }
  return warnings;
}

// Determines whether a CSS file is an FCSS full-bundle that should be purged.
// We match by package name in the path (symlinks resolved by Vite) or by the
// generated-file marker comment that every FCSS CSS file begins with.
function isFcssCssId(id: string, code?: string): boolean {
  const cleanId = (id.split('?')[0] ?? id).replace(/\\/g, '/');
  if (!cleanId.endsWith('.css')) return false;

  // Path-based: workspace resolution puts the file under packages/core or pnpm store.
  if (
    cleanId.includes('/packages/core/dist/') ||
    cleanId.includes('@fcss/core/') ||
    cleanId.includes('/fcss/core/')
  ) {
    return true;
  }

  // Content-based fallback: the generated-file header is the canonical marker.
  if (code && code.startsWith('/**\n * Generated by FCSS.')) {
    return true;
  }

  return false;
}

export function fcss(pluginOptions?: FcssPluginOptions): Plugin {
  let resolvedViteConfig: ResolvedConfig;
  let fcssConfig: FcssViteConfig = {};
  let fcssConfigPath = '';
  let manifestPath = '';
  // Eagerly started in buildStart so it is ready when transform runs.
  let scanPromise: Promise<void> | null = null;
  let purgeCss: ((css: string, id: string) => Promise<string>) | null = null;

  const getContent = () => fcssConfig.content ?? DEFAULT_CONTENT;

  return {
    name: 'vite-plugin-fcss',
    enforce: 'pre',

    async configResolved(config) {
      resolvedViteConfig = config;
      const root = config.root;

      const loaded = await loadFcssConfig(root);
      fcssConfig = { ...loaded.config, ...pluginOptions?.config };
      fcssConfigPath = loaded.configPath;

      try {
        manifestPath = resolveManifestPath(root);
      } catch {
        // Manifest absent at config time; warn in buildStart.
      }
    },

    async buildStart() {
      if (!manifestPath) {
        this.warn(
          '[@fcss/vite] No FCSS manifest found. Install @fcss/core as a project dependency.',
        );
        return;
      }

      const root = resolvedViteConfig.root;
      const content = getContent();
      const currentManifestPath = manifestPath;

      if (resolvedViteConfig.command !== 'build') {
        // Dev mode: scan once and emit dynamic-fragment warnings.
        try {
          const { scan } = await import('@fcss/scanner');
          const manifestRaw = fs.readFileSync(currentManifestPath, 'utf8');
          const manifest = JSON.parse(manifestRaw) as Array<{
            className: string;
            selector: string;
          }>;
          const result = await scan({ content, manifest, cwd: root });
          for (const w of result.report.dynamicWarnings) {
            console.warn(
              `[@fcss/vite] Dynamic class fragment — FCSS cannot statically analyse this; it will be purged in production.\n` +
                `  File: ${w.file}:${w.line}\n` +
                `  Fragment: \`${w.fragment}\`\n` +
                `  Fix: use a static class map instead of template literals.`,
            );
          }
        } catch (err) {
          this.warn(`[@fcss/vite] Dev scan failed: ${String(err)}`);
        }
        return;
      }

      // Production: eagerly set up the purge function so transform can call it.
      // We import lazily to keep these CJS-backed modules out of Vite's config bundle.
      scanPromise = (async () => {
        const [{ default: postcss }, { default: fcssPostcss }] = await Promise.all([
          import('postcss'),
          import('@fcss/postcss'),
        ]);

        const safelistExact =
          fcssConfig.safelist?.filter((s): s is string => typeof s === 'string') ?? [];
        const safelistPatterns =
          fcssConfig.safelist
            ?.filter((s): s is FcssSafelistPattern => typeof s === 'object' && 'pattern' in s)
            .map((s) => s.pattern) ?? [];

        const pluginOpts = {
          manifest: currentManifestPath,
          content,
          cwd: root,
          report: true as const,
          ...(safelistExact.length > 0 || safelistPatterns.length > 0
            ? { safelist: { exact: safelistExact, patterns: safelistPatterns } }
            : {}),
        };

        purgeCss = async (css: string, id: string): Promise<string> => {
          try {
            const result = await postcss([fcssPostcss(pluginOpts)]).process(css, { from: id });
            return result.css;
          } catch (err) {
            console.warn(`[@fcss/vite] Purge failed for "${id}": ${String(err)}`);
            return css;
          }
        };
      })();
    },

    async transform(code, id) {
      if (resolvedViteConfig.command !== 'build') return null;
      if (!isFcssCssId(id, code)) return null;
      if (!scanPromise) return null;

      // Wait for buildStart to finish setting up the purge function.
      await scanPromise;

      if (!purgeCss) return null;

      const purged = await purgeCss(code, id);
      return { code: purged, map: null };
    },

    handleHotUpdate({ file, server }) {
      if (fcssConfigPath && path.resolve(file) === path.resolve(fcssConfigPath)) {
        console.log('[@fcss/vite] fcss.config.ts changed — triggering full reload.');
        server.ws.send({ type: 'full-reload' });
        return [];
      }

      const ext = path.extname(file).toLowerCase();
      const isContent = ['.tsx', '.ts', '.jsx', '.js', '.html'].includes(ext);

      if (isContent && fs.existsSync(file)) {
        const source = fs.readFileSync(file, 'utf8');
        const warnings = collectDynamicWarnings(source, file);
        for (const w of warnings) {
          console.warn(
            `[@fcss/vite] Dynamic class fragment — will be purged in production.\n` +
              `  File: ${w.file}:${w.line}\n` +
              `  Fragment: ${w.fragment}\n` +
              `  Fix: use a static class map instead of template literals.`,
          );
        }
      }

      return undefined;
    },

    configureServer(server) {
      if (fcssConfigPath && fs.existsSync(fcssConfigPath)) {
        server.watcher.add(fcssConfigPath);
      }
    },
  };
}
