// @file packages/postcss/tests/integration.test.ts
// @description Integration tests for the @fcss/postcss plugin.
// @layer tests
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import postcss from 'postcss';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { fileURLToPath } from 'node:url';
import fcssPlugin from '../src/plugin.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Use the real core manifest
const MANIFEST_PATH = path.resolve(__dirname, '../../../packages/core/dist/manifest.json');
const CORE_DIST = path.resolve(__dirname, '../../../packages/core/dist');

let tmpDir = '';
let manifest: Array<{ className: string; selector: string }> = [];

beforeAll(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fcss-postcss-test-'));

  if (fs.existsSync(MANIFEST_PATH)) {
    manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8')) as Array<{
      className: string;
      selector: string;
    }>;
  }
});

afterAll(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

function writeFixture(name: string, content: string): string {
  const p = path.join(tmpDir, name);
  fs.writeFileSync(p, content, 'utf8');
  return p;
}

function buildCssFromManifest(selectors: Array<{ selector: string; declaration: string }>): string {
  const lines = ['/**\n * Generated by FCSS.\n * Do not edit this file manually.\n */'];
  for (const s of selectors) {
    lines.push(`${s.selector} { ${s.declaration} }`);
  }
  return lines.join('\n');
}

let testCounter = 0;

async function processWithPlugin(
  css: string,
  contentFiles: Record<string, string>,
  safelist?: { exact?: string[]; patterns?: RegExp[] },
): Promise<string> {
  if (!fs.existsSync(MANIFEST_PATH)) {
    return css;
  }

  // Unique subdirectory per invocation to avoid cross-test file pollution
  const subDir = path.join(tmpDir, `t${++testCounter}`);
  fs.mkdirSync(subDir, { recursive: true });

  const paths: string[] = [];
  for (const [name, content] of Object.entries(contentFiles)) {
    const p = path.join(subDir, name);
    fs.writeFileSync(p, content, 'utf8');
    paths.push(p);
  }

  const result = await postcss([
    fcssPlugin({
      manifest: MANIFEST_PATH,
      content: paths,
      ...(safelist !== undefined ? { safelist } : {}),
    }),
  ]).process(css, { from: undefined });

  return result.css;
}

describe('manifest loading', () => {
  it('throws a clear error when manifest file is missing', async () => {
    const css = '.display--none { display: none }';
    writeFixture('test.html', '<div class="display--none"></div>');

    const plugin = fcssPlugin({
      manifest: '/nonexistent/path/manifest.json',
      content: [`${tmpDir}/**/*.html`],
      cwd: tmpDir,
    });

    await expect(postcss([plugin]).process(css, { from: undefined })).rejects.toThrow(
      /Cannot load manifest/,
    );
  });
});

describe('content configuration', () => {
  it('throws when no content patterns provided', async () => {
    if (!fs.existsSync(MANIFEST_PATH)) return;

    const plugin = fcssPlugin({
      manifest: MANIFEST_PATH,
      content: [],
    });

    await expect(
      postcss([plugin]).process('.display--none { display: none }', { from: undefined }),
    ).rejects.toThrow(/No content paths/);
  });
});

describe('used vs unused selectors', () => {
  it('retains used FCSS selectors and removes unused ones', async () => {
    if (!manifest.length) return;

    const usedEntry = manifest[0];
    const unusedEntry = manifest[1];
    if (!usedEntry || !unusedEntry) return;

    const css = buildCssFromManifest([
      { selector: usedEntry.selector, declaration: 'display: flex' },
      { selector: unusedEntry.selector, declaration: 'display: none' },
    ]);

    const htmlContent = `<div class="${usedEntry.className}"></div>`;
    const result = await processWithPlugin(css, { 'used.html': htmlContent });

    expect(result).toContain(usedEntry.selector);
    expect(result).not.toContain(unusedEntry.selector);
  });

  it('preserves user CSS (non-FCSS selectors) unconditionally', async () => {
    if (!manifest.length) return;

    const entry = manifest[0];
    if (!entry) return;

    const css = [
      `${entry.selector} { display: flex }`,
      `.my-custom-component { color: hotpink; font-size: 16px }`,
      `.user-button:hover { background: blue }`,
    ].join('\n');

    // Empty HTML — no FCSS classes used
    const result = await processWithPlugin(css, { 'empty.html': '<div></div>' });

    expect(result).toContain('.my-custom-component');
    expect(result).toContain('.user-button:hover');
    expect(result).not.toContain(entry.selector);
  });
});

describe('@media removal', () => {
  it('removes empty @media blocks after child rules are removed', async () => {
    if (!manifest.length) return;

    const entry = manifest.find((e) => e.className.startsWith('sm-'));
    if (!entry) return;

    const css = `@media (min-width: 576px) {\n${entry.selector} { display: flex }\n}`;
    const result = await processWithPlugin(css, { 'nomatch.html': '<div></div>' });

    expect(result).not.toContain('@media (min-width: 576px)');
    expect(result.trim()).toBe('');
  });

  it('retains @media block when at least one child rule is kept', async () => {
    if (!manifest.length) return;

    const smEntry = manifest.find((e) => e.className.startsWith('sm-'));
    if (!smEntry) return;

    const css = `@media (min-width: 576px) {\n${smEntry.selector} { display: flex }\n}`;
    const result = await processWithPlugin(css, {
      'used.html': `<div class="${smEntry.className}"></div>`,
    });

    expect(result).toContain('@media (min-width: 576px)');
    expect(result).toContain(smEntry.selector);
  });
});

describe('safelist', () => {
  it('exact safelist retains class even when not in source files', async () => {
    if (!manifest.length) return;

    const entry = manifest[0];
    const unused = manifest[1];
    if (!entry || !unused) return;

    const css = `${unused.selector} { display: none }`;
    const result = await processWithPlugin(
      css,
      { 'empty.html': '<div></div>' },
      {
        exact: [unused.className],
      },
    );

    expect(result).toContain(unused.selector);
  });

  it('pattern safelist retains classes matching pattern', async () => {
    if (!manifest.length) return;

    const displayEntries = manifest.filter((e) => e.className.startsWith('display--'));
    if (displayEntries.length < 2) return;

    const firstTwo = displayEntries.slice(0, 2);
    const css = firstTwo.map((e) => `${e.selector} { display: flex }`).join('\n');

    const result = await processWithPlugin(
      css,
      { 'empty.html': '<div></div>' },
      {
        patterns: [/^display--/],
      },
    );

    for (const entry of firstTwo) {
      expect(result).toContain(entry.selector);
    }
  });
});

describe('variable retention', () => {
  it('user CSS with --fcss-color-* custom properties is preserved', async () => {
    if (!manifest.length) return;

    const css = [
      ':root { --fcss-color-blue: #0d6efd }',
      '.user-heading { color: var(--fcss-color-blue) }',
    ].join('\n');

    const result = await processWithPlugin(css, { 'empty.html': '<div></div>' });

    expect(result).toContain('--fcss-color-blue');
    expect(result).toContain('.user-heading');
  });
});

describe('purge report', () => {
  it('report=true produces no error and logs stats', async () => {
    if (!manifest.length) return;

    const entry = manifest[0];
    if (!entry) return;

    const css = `${entry.selector} { display: flex }`;
    writeFixture('report-test.html', `<div class="${entry.className}"></div>`);

    const plugin = fcssPlugin({
      manifest: MANIFEST_PATH,
      content: [`${tmpDir}/report-test.html`],
      cwd: tmpDir,
      report: true,
    });

    // Should not throw
    await expect(postcss([plugin]).process(css, { from: undefined })).resolves.toBeDefined();
  });
});

describe('vanilla fixture production build', () => {
  it('processes core utilities.css and produces a smaller output', async () => {
    const utilitiesPath = path.join(CORE_DIST, 'utilities.css');
    if (!fs.existsSync(utilitiesPath) || !fs.existsSync(MANIFEST_PATH)) return;

    const utilitiesCss = fs.readFileSync(utilitiesPath, 'utf8');
    const vanillaHtml = path.resolve(__dirname, '../../../examples/vanilla/index.html');

    if (!fs.existsSync(vanillaHtml)) return;

    const htmlContent = fs.readFileSync(vanillaHtml, 'utf8');
    const htmlFile = writeFixture('vanilla.html', htmlContent);

    const plugin = fcssPlugin({
      manifest: MANIFEST_PATH,
      content: [htmlFile],
      report: false,
    });

    const result = await postcss([plugin]).process(utilitiesCss, { from: undefined });
    const purgedSize = Buffer.byteLength(result.css, 'utf8');
    const originalSize = Buffer.byteLength(utilitiesCss, 'utf8');

    expect(purgedSize).toBeLessThan(originalSize);

    // The vanilla fixture uses a handful of classes — purged output should be tiny
    const reductionPct = ((1 - purgedSize / originalSize) * 100).toFixed(1);
    console.log(
      `  Vanilla purge: ${(originalSize / 1024).toFixed(1)} KB → ${(purgedSize / 1024).toFixed(1)} KB (${reductionPct}% reduction)`,
    );
  });
});
