// @file packages/generator/src/bundles.ts
// @description Bundle builder — assembles generated rules into the FCSS output file structure.
// @layer tools
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import { GENERATED_FILE_HEADER } from './generate.js';
import type { GenerateResult, GeneratedRule } from './generate.js';
import type { ManifestEntry } from './manifest.js';

export interface BundleOutput {
  'utilities.css': string;
  'states/pseudo.css': string;
  'states/aria.css': string;
  'responsive/sm.css': string;
  'responsive/md.css': string;
  'responsive/lg.css': string;
  'responsive/xl.css': string;
  'responsive/xxl.css': string;
  'full.css': string;
  'manifest.json': string;
  [key: string]: string;
}

const BREAKPOINT_BY_WIDTH: Record<string, string> = {
  '576': 'sm',
  '768': 'md',
  '992': 'lg',
  '1200': 'xl',
  '1400': 'xxl',
};

type RuleType = 'base' | 'pseudo' | 'aria';

function classifyRule(rule: GeneratedRule): RuleType {
  if (rule.selector.includes('[aria-')) return 'aria';
  // pseudo selectors end with an unescaped colon + word: e.g. `:hover` at the tail
  if (/:[a-z-]+$/.test(rule.selector)) return 'pseudo';
  return 'base';
}

function getBreakpointName(mediaQuery: string): string {
  const match = /min-width:\s*(\d+)px/.exec(mediaQuery);
  if (!match || !match[1]) return 'sm';
  return BREAKPOINT_BY_WIDTH[match[1]] ?? 'sm';
}

function formatRule(rule: GeneratedRule): string {
  return `${rule.selector} { ${rule.declaration} }\n`;
}

function buildFile(rules: GeneratedRule[]): string {
  if (rules.length === 0) return `${GENERATED_FILE_HEADER}\n`;
  return `${GENERATED_FILE_HEADER}\n${rules.map(formatRule).join('')}`;
}

function buildResponsiveFile(rules: GeneratedRule[], mediaQuery: string): string {
  if (rules.length === 0) return `${GENERATED_FILE_HEADER}\n`;
  const body = rules.map(formatRule).join('');
  return `${GENERATED_FILE_HEADER}\n${mediaQuery} {\n${body}}\n`;
}

function buildManifestFile(manifest: ManifestEntry[]): string {
  return `/* Generated by FCSS. Do not edit. */\n${JSON.stringify(manifest, null, 2)}\n`;
}

export function buildBundles(result: GenerateResult): BundleOutput {
  const baseRules: GeneratedRule[] = [];
  const pseudoRules: GeneratedRule[] = [];
  const ariaRules: GeneratedRule[] = [];
  const responsiveRules: Map<string, GeneratedRule[]> = new Map([
    ['sm', []],
    ['md', []],
    ['lg', []],
    ['xl', []],
    ['xxl', []],
  ]);
  const responsiveMediaQueries: Map<string, string> = new Map();

  for (const rule of result.rules) {
    if (rule.mediaQuery) {
      const bp = getBreakpointName(rule.mediaQuery);
      const bucket = responsiveRules.get(bp);
      if (bucket) bucket.push(rule);
      if (!responsiveMediaQueries.has(bp)) responsiveMediaQueries.set(bp, rule.mediaQuery);
    } else {
      const type = classifyRule(rule);
      if (type === 'aria') ariaRules.push(rule);
      else if (type === 'pseudo') pseudoRules.push(rule);
      else baseRules.push(rule);
    }
  }

  const smRules = responsiveRules.get('sm') ?? [];
  const mdRules = responsiveRules.get('md') ?? [];
  const lgRules = responsiveRules.get('lg') ?? [];
  const xlRules = responsiveRules.get('xl') ?? [];
  const xxlRules = responsiveRules.get('xxl') ?? [];

  const utilitiesCss = buildFile(baseRules);
  const pseudoCss = buildFile(pseudoRules);
  const ariaCss = buildFile(ariaRules);
  const smCss = buildResponsiveFile(smRules, responsiveMediaQueries.get('sm') ?? '@media (min-width: 576px)');
  const mdCss = buildResponsiveFile(mdRules, responsiveMediaQueries.get('md') ?? '@media (min-width: 768px)');
  const lgCss = buildResponsiveFile(lgRules, responsiveMediaQueries.get('lg') ?? '@media (min-width: 992px)');
  const xlCss = buildResponsiveFile(xlRules, responsiveMediaQueries.get('xl') ?? '@media (min-width: 1200px)');
  const xxlCss = buildResponsiveFile(xxlRules, responsiveMediaQueries.get('xxl') ?? '@media (min-width: 1400px)');

  const fullCss = [utilitiesCss, pseudoCss, ariaCss, smCss, mdCss, lgCss, xlCss, xxlCss].join('');

  return {
    'utilities.css': utilitiesCss,
    'states/pseudo.css': pseudoCss,
    'states/aria.css': ariaCss,
    'responsive/sm.css': smCss,
    'responsive/md.css': mdCss,
    'responsive/lg.css': lgCss,
    'responsive/xl.css': xlCss,
    'responsive/xxl.css': xxlCss,
    'full.css': fullCss,
    'manifest.json': buildManifestFile(result.manifest),
  };
}
