// @file packages/generator/src/generate.ts
// @description Main generation pipeline — produces FCSS utility rules and manifest from the spec.
// @layer tools
// @created Diego Lafuente <diego.lafuente@cognativinc.com>

import {
  FCSS_PROPERTIES,
  FCSS_BREAKPOINTS,
  FCSS_LENGTH_SCALE,
  FCSS_PERCENTAGE_SCALE,
  FCSS_ARIA_STATES,
} from '@fcss/spec';
import type { FcssPropertyDefinition, FcssValueDefinition, FcssNumericBehavior } from '@fcss/spec';
import {
  buildBaseClassName,
  buildPseudoClassName,
  buildAriaClassName,
  buildResponsiveClassName,
  buildResponsivePseudoClassName,
  buildResponsiveAriaClassName,
} from './class-name.js';
import { buildSelector } from './selector.js';
import { buildDeclaration } from './declaration.js';
import { buildManifestEntry } from './manifest.js';
import type { ManifestEntry, ManifestCondition } from './manifest.js';

export const GENERATED_FILE_HEADER = `/**\n * Generated by FCSS.\n * Do not edit this file manually.\n */`;

export interface GeneratedRule {
  selector: string;
  declaration: string;
  mediaQuery?: string;
  category: string;
}

export interface GenerateResult {
  rules: GeneratedRule[];
  manifest: ManifestEntry[];
}

// Numeric scales for each behavior type
const INTEGER_SCALE: FcssValueDefinition[] = [
  -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24,
].map((n) => ({ classValue: String(n), cssValue: String(n) }));

const POSITIVE_INTEGER_SCALE: FcssValueDefinition[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12].map((n) => ({
  classValue: String(n),
  cssValue: String(n),
}));

const NUMBER_SCALE: FcssValueDefinition[] = [
  0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95,
  1,
].map((n) => ({ classValue: String(n), cssValue: String(n) }));

function getNumericScale(behavior: FcssNumericBehavior): FcssValueDefinition[] {
  switch (behavior) {
    case 'length':
      return [...FCSS_LENGTH_SCALE];
    case 'percentage':
      return [...FCSS_PERCENTAGE_SCALE];
    case 'length-percentage':
      return [...FCSS_LENGTH_SCALE, ...FCSS_PERCENTAGE_SCALE];
    case 'integer':
      return INTEGER_SCALE;
    case 'positive-integer':
      return POSITIVE_INTEGER_SCALE;
    case 'number':
      return NUMBER_SCALE;
    default:
      return [];
  }
}

// Build aria states lookup: attribute → values[]
const ARIA_VALUES_MAP = new Map<string, readonly string[]>(
  FCSS_ARIA_STATES.map((s) => [s.attribute, s.values]),
);

// Builds a ManifestEntry without setting deprecated if it is undefined (exactOptionalPropertyTypes).
function makeEntry(params: {
  className: string;
  selector: string;
  property: string;
  value: string;
  condition?: ManifestCondition;
  breakpoint?: string;
  category: string;
  isDeprecated: boolean | undefined;
  source: string;
}): ManifestEntry {
  const base = {
    className: params.className,
    selector: params.selector,
    property: params.property,
    value: params.value,
    category: params.category,
    source: params.source,
  };
  return buildManifestEntry({
    ...base,
    ...(params.condition !== undefined ? { condition: params.condition } : {}),
    ...(params.breakpoint !== undefined ? { breakpoint: params.breakpoint } : {}),
    ...(params.isDeprecated === true ? { deprecated: true } : {}),
  });
}

export function generate(properties: readonly FcssPropertyDefinition[] = FCSS_PROPERTIES): GenerateResult {
  const rules: GeneratedRule[] = [];
  const manifest: ManifestEntry[] = [];
  const seenSelectors = new Set<string>();

  function addRule(rule: GeneratedRule, entry: ManifestEntry): void {
    if (seenSelectors.has(rule.selector)) {
      throw new Error(`Duplicate selector detected: ${rule.selector}`);
    }
    if (rule.declaration.includes('\n')) {
      throw new Error(`Multi-declaration rule detected: ${rule.declaration}`);
    }
    seenSelectors.add(rule.selector);
    rules.push(rule);
    manifest.push(entry);
  }

  for (const prop of properties) {
    if (prop.status !== 'supported' && prop.status !== 'preset-only') continue;

    const explicitClassValues = new Set(prop.values.map((v) => v.classValue));
    const allValues: FcssValueDefinition[] = [...prop.values];

    if (prop.numericBehavior) {
      for (const sv of getNumericScale(prop.numericBehavior)) {
        if (!explicitClassValues.has(sv.classValue)) {
          allValues.push(sv);
        }
      }
    }

    for (const val of allValues) {
      const cssValue = resolveValue(val, prop.numericBehavior);

      // ── Base ──
      const baseClass = buildBaseClassName(prop.property, val.classValue);
      const baseSel = buildSelector(baseClass);
      addRule(
        { selector: baseSel, declaration: buildDeclaration(prop.property, cssValue), category: prop.category },
        makeEntry({
          className: baseClass,
          selector: baseSel,
          property: prop.property,
          value: cssValue,
          category: prop.category,
          isDeprecated: val.deprecated,
          source: prop.specification,
        }),
      );

      // ── Pseudo variants ──
      for (const pseudo of prop.supportedPseudoClasses) {
        const cls = buildPseudoClassName(prop.property, val.classValue, pseudo);
        const sel = buildSelector(cls, pseudo);
        addRule(
          { selector: sel, declaration: buildDeclaration(prop.property, cssValue), category: prop.category },
          makeEntry({
            className: cls,
            selector: sel,
            property: prop.property,
            value: cssValue,
            condition: { type: 'pseudo', value: pseudo },
            category: prop.category,
            isDeprecated: val.deprecated,
            source: prop.specification,
          }),
        );
      }

      // ── ARIA variants ──
      for (const ariaAttr of prop.supportedAriaStates) {
        const ariaValues = ARIA_VALUES_MAP.get(ariaAttr);
        if (!ariaValues) continue;
        for (const ariaValue of ariaValues) {
          const cls = buildAriaClassName(prop.property, val.classValue, ariaAttr, ariaValue);
          const sel = buildSelector(cls, undefined, ariaAttr, ariaValue);
          addRule(
            { selector: sel, declaration: buildDeclaration(prop.property, cssValue), category: prop.category },
            makeEntry({
              className: cls,
              selector: sel,
              property: prop.property,
              value: cssValue,
              condition: { type: 'aria', attribute: ariaAttr, value: ariaValue },
              category: prop.category,
              isDeprecated: val.deprecated,
              source: prop.specification,
            }),
          );
        }
      }

      if (!prop.supportsResponsive) continue;

      // ── Responsive variants ──
      for (const bp of FCSS_BREAKPOINTS) {
        const mq = `@media (min-width: ${bp.minWidth}px)`;

        const rCls = buildResponsiveClassName(bp.name, prop.property, val.classValue);
        const rSel = buildSelector(rCls);
        addRule(
          {
            selector: rSel,
            declaration: buildDeclaration(prop.property, cssValue),
            mediaQuery: mq,
            category: prop.category,
          },
          makeEntry({
            className: rCls,
            selector: rSel,
            property: prop.property,
            value: cssValue,
            breakpoint: bp.name,
            category: prop.category,
            isDeprecated: val.deprecated,
            source: prop.specification,
          }),
        );

        for (const pseudo of prop.supportedPseudoClasses) {
          const cls = buildResponsivePseudoClassName(bp.name, prop.property, val.classValue, pseudo);
          const sel = buildSelector(cls, pseudo);
          addRule(
            {
              selector: sel,
              declaration: buildDeclaration(prop.property, cssValue),
              mediaQuery: mq,
              category: prop.category,
            },
            makeEntry({
              className: cls,
              selector: sel,
              property: prop.property,
              value: cssValue,
              condition: { type: 'pseudo', value: pseudo },
              breakpoint: bp.name,
              category: prop.category,
              isDeprecated: val.deprecated,
              source: prop.specification,
            }),
          );
        }

        for (const ariaAttr of prop.supportedAriaStates) {
          const ariaValues = ARIA_VALUES_MAP.get(ariaAttr);
          if (!ariaValues) continue;
          for (const ariaValue of ariaValues) {
            const cls = buildResponsiveAriaClassName(bp.name, prop.property, val.classValue, ariaAttr, ariaValue);
            const sel = buildSelector(cls, undefined, ariaAttr, ariaValue);
            addRule(
              {
                selector: sel,
                declaration: buildDeclaration(prop.property, cssValue),
                mediaQuery: mq,
                category: prop.category,
              },
              makeEntry({
                className: cls,
                selector: sel,
                property: prop.property,
                value: cssValue,
                condition: { type: 'aria', attribute: ariaAttr, value: ariaValue },
                breakpoint: bp.name,
                category: prop.category,
                isDeprecated: val.deprecated,
                source: prop.specification,
              }),
            );
          }
        }
      }
    }
  }

  return { rules, manifest };
}

function resolveValue(val: FcssValueDefinition, numericBehavior: FcssNumericBehavior | undefined): string {
  if (!numericBehavior) return val.cssValue;
  // If cssValue is already a properly-formed CSS value (has a unit suffix or is a non-numeric string), use it.
  const isRawNumber = /^-?(\d+\.?\d*|\.\d+)$/.test(val.cssValue) && !val.cssValue.endsWith('%');
  if (!isRawNumber) return val.cssValue;

  const num = parseFloat(val.cssValue);
  switch (numericBehavior) {
    case 'length':
    case 'length-percentage':
      return num === 0 ? '0' : `${num}px`;
    case 'integer':
    case 'positive-integer':
    case 'number':
      return val.cssValue;
    case 'percentage':
      return val.cssValue;
    default:
      return val.cssValue;
  }
}
